### ISSUE TITLE
Reconsider SyncFusion ComBoBoxes

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryBuilder-2#441]
**Is your feature request related to a problem? Please describe.**
SyncFusion has been very good for us because it fixed a major problem with Microsoft's ComboBoxes- the controls were rendered unacceptably clipped.  SyncFusion's also been generous with its open-source license.

However, there's a problem with using the product: it makes it difficult for others to fork and use StoryBuilder because they need their own personal SyncFusion licenses. (It should be noted that this is also a problem with elmah.io and secrets.)  

**Describe the solution you'd like**
Test to see if it's possible to switch back to Microsoft's ComboBox.

**Describe alternatives you've considered**

**Additional context**
There is one additional consideration: the Purpose of Scene is a multi-valued ComboBox, which the Microsoft ComboBox doesn't support. However, it should be possible to switch to a ListView with checkboxes, and show them as a tooltip.

**Comment by Rarisma** [comment]
This has been considered, and as Microsoft has fixed thier combobox clipping a previous version of WinAppSDK (1.2 I believe).
We have decided to move away from using syncfusion due the issues with forking and handling secrets, now that the default comboboxes are fixed and as we do not use any extra features of SF ComboBoxes (with the exception of Purpose of Scene which has been rewritten) we have removed all syncfusion related controls.

As such this issue/enhancement has been fixed since #464.
